create table goal (id integer generated by default as identity, description varchar(255), target varchar(255), title varchar(25) not null, primary key (id))
create table role (id integer generated by default as identity, code varchar(255), name varchar(255), primary key (id))
create table user (id integer generated by default as identity, active boolean not null, password varchar(60), username varchar(255), primary key (id))
create table user_roles (user_id integer not null, roles_id integer not null)
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user
